from .conditional_flow import (
    NODE_CLASS_MAPPINGS as _FLOW_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _FLOW_NAMES,
)
from .audio_utils import (
    NODE_CLASS_MAPPINGS as _AUDIO_NODES,
    NODE_DISPLAY_NAME_MAPPINGS as _AUDIO_NAMES,
)

NODE_CLASS_MAPPINGS = {**_FLOW_NODES, **_AUDIO_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_FLOW_NAMES, **_AUDIO_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
